/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.79
 * Generated at: 2022-06-04 23:17:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.produtos;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.stream.Stream;
import br.com.model.TipoProduto;
import br.com.DAO.TipoProdutoDAO;
import br.com.model.Fornecedor;
import br.com.DAO.FornecedorDAO;
import br.com.model.Produto;
import java.util.ArrayList;
import br.com.DAO.ProdutoDAO;

public final class listarProdutos_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("br.com.model.Produto");
    _jspx_imports_classes.add("java.util.stream.Stream");
    _jspx_imports_classes.add("br.com.DAO.FornecedorDAO");
    _jspx_imports_classes.add("br.com.model.Fornecedor");
    _jspx_imports_classes.add("br.com.DAO.ProdutoDAO");
    _jspx_imports_classes.add("br.com.model.TipoProduto");
    _jspx_imports_classes.add("br.com.DAO.TipoProdutoDAO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>Comprar</title>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        \n");
      out.write("            <table border=\"1\" cellspacing=\"0\" cellpadding=\"0\">\n");
      out.write("                <tr>\n");
      out.write("                    <th>Nome</th>\n");
      out.write("                    <th><a href=\"/ProjetoLoja/fornecedor/listarFornecedor.jsp?voltaLista=1\">Fornecedor</a></th>\n");
      out.write("                    <th><a href=\"/ProjetoLoja/tipos/listarTipos.jsp?voltaLista=1\">Tipo</a></th>\n");
      out.write("                    <th>Valor</th>\n");
      out.write("                </tr>      \n");
      out.write("                        \n");
      out.write("                         ");

            try {
                ProdutoDAO produtoDAO = new ProdutoDAO();
                ArrayList<Produto> lista = produtoDAO.RecuperaProduto();
                Produto produto = new Produto();
                   for (int num = 0; num < lista.size(); num++) {
                    out.print("<tr>");  
                    out.print("<td> " + lista.get(num).getNome_produto()+ "</td>");
                    out.print("<td> " + produto.RecuperaNomeFornecedor(lista.get(num).getFk_fornecedor())+ "</td>");
                    out.print("<td> " + produto.RecuperaNomeTipo(lista.get(num).getFk_tipo_produto())+ "</td>");
                    out.print("<td> " + lista.get(num).getValor()+ "</td>");
                    out.print("</tr>");
                    }               
            } catch (Exception e) {
            }
        
      out.write("\n");
      out.write("            </table>\n");
      out.write("            <br><button type=\"submit\"><a href=\"produto.jsp\">Cadastrar Produto</a></button>\n");
      out.write("            <button type=\"submit\"><a href=\"/ProjetoLoja/fornecedor/fornecedor.jsp\">Cadastrar Fornecedor</a></button>\n");
      out.write("            <button type=\"submit\"><a href=\"/ProjetoLoja/tipos/tipo.jsp\">Cadastrar Novo Tipo</a></button> <br>\n");
      out.write("            <br><button type=\"submit\"><a href=\"/ProjetoLoja\">Voltar</a></button>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
